name: Java CI with Maven and JAR Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published] # Запускать workflow при создании нового релиза

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build the project and create JAR
      run: mvn --batch-mode --update-snapshots package

    - name: Upload JAR as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: application.jar
        path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download the JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: application.jar
        path: target

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_id }} # Используем ID запуска как тег
        release_name: Release v${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/*.jar
        asset_name: application.jar
        asset_content_type: application/java-archive
